steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'sh'
    args:
      - '-c'
      - |
        echo "Retrieving secrets..."
        export REFRESH_TOKEN=$(gcloud secrets versions access latest --secret=REFRESH_TOKEN)
        export CLIENT_ID=$(gcloud secrets versions access latest --secret=CLIENT_ID)
        export CLIENT_SECRET=$(gcloud secrets versions access latest --secret=CLIENT_SECRET)
        echo "REFRESH_TOKEN=$REFRESH_TOKEN" >> .env
        echo "CLIENT_ID=$CLIENT_ID" >> .env
        echo "CLIENT_SECRET=$CLIENT_SECRET" >> .env

  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/wedding-planner-app', '.']
    secretEnv: ['CLIENT_ID', 'CLIENT_SECRET', 'REFRESH_TOKEN']
    env:
      - 'CLIENT_ID=$CLIENT_ID'
      - 'CLIENT_SECRET=$CLIENT_SECRET'
      - 'REFRESH_TOKEN=$REFRESH_TOKEN'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wedding-planner-app']

images:
  - 'gcr.io/$PROJECT_ID/wedding-planner-app'

availableSecrets:
  secretManager:
    - versionName: "projects/wedding-410109/secrets/CLIENT_ID/versions/1"
      env: "CLIENT_ID"
    - versionName: "projects/wedding-410109/secrets/CLIENT_SECRET/versions/1"
      env: "CLIENT_SECRET"
    - versionName: "projects/wedding-410109/secrets/REFRESH_TOKEN/versions/1"
      env: "REFRESH_TOKEN"
