steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        echo "Retrieving secrets..."
        echo "REFRESH_TOKEN=$(gcloud secrets versions access latest --secret=REFRESH_TOKEN)" >> .env
        echo "CLIENT_ID=$(gcloud secrets versions access latest --secret=CLIENT_ID)" >> .env
        echo "CLIENT_SECRET=$(gcloud secrets versions access latest --secret=CLIENT_SECRET)" >> .env

  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/wedding-planner-app'
      - '--build-arg'
      - 'REFRESH_TOKEN=${_REFRESH_TOKEN}'
      - '--build-arg'
      - 'CLIENT_ID=${_CLIENT_ID}'
      - '--build-arg'
      - 'CLIENT_SECRET=${_CLIENT_SECRET}'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wedding-planner-app']

images:
  - 'gcr.io/$PROJECT_ID/wedding-planner-app'

substitutions:
  _REFRESH_TOKEN: ${_REFRESH_TOKEN}
  _CLIENT_ID: ${_CLIENT_ID}
  _CLIENT_SECRET: ${_CLIENT_SECRET}

availableSecrets:
  secretManager:
    - versionName: projects/wedding-410109/secrets/CLIENT_ID/versions/latest
      env: _CLIENT_ID
    - versionName: projects/wedding-410109/secrets/CLIENT_SECRET/versions/latest
      env: _CLIENT_SECRET
    - versionName: projects/wedding-410109/secrets/REFRESH_TOKEN/versions/latest
      env: _REFRESH_TOKEN