steps:
  # Access secrets and pass them as build args
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker build \
          --build-arg REFRESH_TOKEN="$${REFRESH_TOKEN}" \
          --build-arg CLIENT_ID="$${CLIENT_ID}" \
          --build-arg CLIENT_SECRET="$${CLIENT_SECRET}" \
          -t gcr.io/$PROJECT_ID/wedding-planner-app .
    secretEnv: ['REFRESH_TOKEN', 'CLIENT_ID', 'CLIENT_SECRET']

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/wedding-planner-app']

  # Deploy container image to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
    - 'run'
    - 'deploy'
    - 'wedding-planner-app'
    - '--image'
    - 'gcr.io/$PROJECT_ID/wedding-planner-app'
    - '--region'
    - 'us-central1'  # replace with your preferred region
    - '--platform'
    - 'managed'
    - '--allow-unauthenticated'
    - '--set-secrets=REFRESH_TOKEN=REFRESH_TOKEN:latest,CLIENT_ID=CLIENT_ID:latest,CLIENT_SECRET=CLIENT_SECRET:latest'

images:
  - 'gcr.io/$PROJECT_ID/wedding-planner-app'

availableSecrets:
  secretManager:
    - versionName: projects/wedding-410109/secrets/REFRESH_TOKEN/versions/latest
      env: 'REFRESH_TOKEN'
    - versionName: projects/wedding-410109/secrets/CLIENT_ID/versions/latest
      env: 'CLIENT_ID'
    - versionName: projects/wedding-410109/secrets/CLIENT_SECRET/versions/latest
      env: 'CLIENT_SECRET'