import { Quicksand } from '@next/font/google'
import Script from 'next/script'
import './globals.css'

const quicksand = Quicksand({
  display: 'swap',
  weight: '400',
  subsets: ['latin']
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html className={quicksand.className} lang="en">
      <head>
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-7N7Z5QT24Z"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
          window.dataLayer = window.dataLayer || [];
          function gtag(){dataLayer.push(arguments);}
          gtag('js', new Date());
        
          gtag('config', 'G-7N7Z5QT24Z');
        `}
        </Script>
        <script />
        <title>Jonathan & Alfrida</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://use.typekit.net/hrz4pax.css" />
      </head>
      <body>{children}</body>
    </html>
  )
}
